### ISSUE TITLE
A convinient way to set some state inside an Env

### ISSUE THREAD

**Issue by ch1c0t** [ch1c0t/hobby-test#1]
Currently, each specification consists of an `Array` of `Exchange`s(executed sequentially). Thus, the only way to set some variable(persisted during all specification' exchanges) is from an exchange:
```yaml
- get:
    path: /

  response:
    body: (@abomination = 'r' + 'o' + 'o' + 't')

  get:
    path: /

  response:
    body: (@abomination)
```

There should be a better way. Like:
```yaml
- set:
    abomination: ('r' + 'o' + 'o' + 't')

- get:
    path: /

  response:
    body: (abomination)
```
which means that a specification will be consisting of an `Array` of more general entities than `Exchange`.
